import os

CHECKWX_API_KEY = os.environ['CHECKWX_API_KEY']
TW_CONSUMER_KEY = os.environ['TW_CONSUMER_KEY']
TW_CONSUMER_SECRET = os.environ['TW_CONSUMER_SECRET']
TW_ACCESS_TOKEN = os.environ['TW_ACCESS_TOKEN']
TW_ACCESS_SECRET = os.environ['TW_ACCESS_SECRET']
